### PR TITLE
fix http timeout handling

### PR DESCRIPTION
**Pull request by jonrios**

### CODE REVIEW

**Review by uhurusurfa — CHANGES_REQUESTED** [review]
Thanks for the PR.
Please revert the pom.xml files to HEAD - I will manage the version bump.

**Review by uhurusurfa — CHANGES_REQUESTED** [review]
Actually, that change is not backwards compatible for people who are already using socket timeoutt so cannot accept it.
Leave socket time out and revove the read timeout since it overrides the connect timeout

**Review by uhurusurfa — CHANGES_REQUESTED** [review]
Please run these commands then commit and push and I will be happy to merge:
git checkout 128a567617 Server/pom.xml
git checkout 128a567617 Remote/pom.xml
git checkout 128a567617 Bundle/pom.xml

**Comment by jonrios** [comment]
Hi @uhurusurfa ,

I apologize for the delay.

As you said I reverted the socket timeout removal and removed the read timeout instead. I also added the socket timeout to the HttpSenderModule to make it configurable for sending modules

**Review by uhurusurfa — APPROVED** [review]
👍  Thanks for the contribution

**Pull request merged**
