### PR TITLE
Support reverse proxies

### PR DESCRIPTION
**Pull request by DevDef**
Try to support reverse proxies by reading X-Real-IP and X-Forwarded-For
HTTP headers.

### CODE REVIEW

**Comment by uhurusurfa** [comment]
Thanks for the contribution. Looks good.

**Comment by uhurusurfa** [comment]
Please change the pull request to go to the "dev" branch

**Comment by DevDef** [comment]
Done as [PR#65](https://github.com/OpenAS2/OpenAs2App/pull/65).
It also contains other commits from your master branch that haven’t been merged to dev branch.
Let me know if you want me to rebase my changes on the dev branch to avoid merging the master commits…

**Comment by DevDef** [comment]
[PR#66](https://github.com/OpenAS2/OpenAs2App/pull/66) contains the same changes but based on dev branch.

**Pull request closed without merging**
